version: 0.0
os: linux
files:
  - source: /
    destination: /home/derana/tamil-client/
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: derana
  ValidateService:
    - location: scripts/revert_permissions.sh
      timeout: 300
      runas: root
